-- 그룹 테이블
CREATE TABLE user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    relation_type VARCHAR(20) NOT NULL,
    owner_id BIGINT NOT NULL,
    invite_code VARCHAR(6) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_groups_invite_code UNIQUE (invite_code),
    CONSTRAINT fk_user_groups_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- 그룹 멤버 테이블
CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES user_groups(id),
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 그룹 궁합 테이블
CREATE TABLE group_compatibilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_a_id BIGINT NOT NULL,
    user_b_id BIGINT NOT NULL,
    score INT NOT NULL,
    content VARCHAR(500) NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_group_compat_group_users_date UNIQUE (group_id, user_a_id, user_b_id, date),
    CONSTRAINT fk_group_compat_group FOREIGN KEY (group_id) REFERENCES user_groups(id),
    CONSTRAINT fk_group_compat_user_a FOREIGN KEY (user_a_id) REFERENCES users(id),
    CONSTRAINT fk_group_compat_user_b FOREIGN KEY (user_b_id) REFERENCES users(id)
);
CREATE INDEX idx_group_compatibility_group_date ON group_compatibilities(group_id, date);
