CREATE TABLE push_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_user_ids TEXT,
    sent_count INT NOT NULL DEFAULT 0,
    fail_count INT NOT NULL DEFAULT 0,
    sent_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
